### PR TITLE
Contrained zoom

### PR DESCRIPTION
**Pull request by dingandrew**
## Description:

Unify the x and y axis check-boxes for all tools.

## Risk Assessment

No known risks or bugs

## Performance Impact

No known or significant performance impact.

## Testing Assessment

Tested each tool to check for correct behavior.

### CODE REVIEW

**Comment by dingandrew** [comment]
It is not possible to lock the rectangle zoom tool to only be a sliver depending on which axis is blocked. The drawing of the rectangle is controlled by bqplot.

**Comment by Amithab** [comment]
brush_interval_selector

Apparently, it was `BrushIntervalSelector` that allows you to do this. My code for that demo is in the `feature_brush_interval_selector` branch. Not sure how to merge it with your changes. It might need the same manipulation PanZoom currently has where you redefine it everytime the checkboxes are updated since you need to choose the orientation and the scale either x/y. I'm not sure if this needs to be part of this PR or not.

**Comment by stevenjswanson** [comment]
Yeah! Nice!

-steve

**Comment by stevenjswanson** [comment]
This works for the "crop" button zoom tool, but not for the reset-zoom button.  It still goes all the way out on both axes.

**Comment by dingandrew** [comment]
I just tested this on the reset button, and I didn't have this issue.

**Comment by dingandrew** [comment]
I added BrushIntervalSelector capabilities, so whenever an axis is locked the zoom selection tool will also lock the highlighting to an axis. I also merged the separate zoom buttons branch into this one, to fix some bugs and merge conflicts . 

This should be ready to merge to main.

**Comment by stevenjswanson** [comment]
I'm not sure I'm seeing the effect of this.  Can you add a screen cap?

**Comment by dingandrew** [comment]
image
Should look like this.

**Pull request merged**
