### PR TITLE
Seperate zoom btns

### PR DESCRIPTION
**Pull request by dingandrew**
## Description:

Add a separate zoom out button.

## Risk Assessment

No known risks or bugs

## Performance Impact

No known or significant performance impact.

## Testing Assessment

Played around with the tool.

### CODE REVIEW

**Comment by Amithab** [comment]
Isn't this just adding to the interaction bar like the panzoom and stuff? Do we want it to be actual buttons like the reset button? Both have their pros and cons like this takes more clicks but you can choose where to zoom, and with actual buttons, you have less clicks but you can only zoom in/out from the center. Which would be better?

**Comment by dingandrew** [comment]
> Isn't this just adding to the interaction bar like the panzoom and stuff? Do we want it to be actual buttons like the reset button? Both have their pros and cons like this takes more clicks but you can choose where to zoom, and with actual buttons, you have less clicks but you can only zoom in/out from the center. Which would be better?

Are you suggesting that the zoom out button should just zoom out from center as opposed to requiring a click?

**Comment by Amithab** [comment]
I'm saying right now there is no zoom in/zoom out button. They're just extra options in the interaction toolbar. The other option is to make it like the reset button which means you wouldn't have control over where to zoom.

**Comment by stevenjswanson** [comment]
@Amithab is right that having to click twice to zoom out is one more click than is strictly necessary.  However, I think it's more consistent to have to select each tool and then use it.  Otherwise, the zoom out tool is different than the others.

Being able to zoom out around a particular point is maybe useful as well.

My bigger issue with the pull request is that if you zoom way in, you can't get all the way back to all the way zoomed out with the zoom out tool.  If I think I should be able to keep zooming out until I can see the whole data set.

**Comment by dingandrew** [comment]
So I fixed the issue of not being able to zoom out, but you need to lock an axis to control it well. Also the zoom out tool does zoom out around a point, although the effect is not very obvious.

**Comment by dingandrew** [comment]
Since this pull request edits the same file as the constrained zoom pull request, I merged this branch over there to make debugging and merging easier. 

TODO: Delete this pull request.

**Pull request closed without merging**
