### PR TITLE
Feature file browser

### PR DESCRIPTION
**Pull request by szl005**
## Description:

Removed old widget system, replaced with file browser
Removed logging, important logging all related to the widgets
Added new `.trace`, `.tags`, `.meta` naming scheme

## Risk Assessment

No known risks or bugs

## Performance Impact
**Be sure to explain how you measured performance impact*  

No known or significant performance impact.

## Testing Assessment

*Please describe what testing has been done.*

Loaded multiple traces using file browser

### CODE REVIEW

**Review by stevenjswanson — CHANGES_REQUESTED** [review]
1. Don't we need something in setup.py or requirements.txt for the chooser module?
2. Instead of a "change" button, let's have a "load" button.  And allow me to re-load the current trace. For instance, if I can regenerate the trace, I need to reload it.  The "change" button is disabled when I try to "change" to the same file.
3. There's no feedback when I successfully select a file that something is happening.  Can we have progress bar for opening?  Or, even better, have the graph area visible all the time rather than appear when I select a file.
4.  It also occurred to me that once we have the command line thing working, the file choose could be invoked like this:
`file = pick_file()`
and then we could say
`load_file(file)`
That would decouple the file chooser from moneta itself.
We could also have
`choose_trace_and_load()` which would display the chooser and then load the file.

**Comment by Amithab** [comment]
Screen Shot 2021-05-09 at 11 28 34 AM

Text seems to be less opaque in the dropdowns. I don't remember when this changed

**Comment by stevenjswanson** [comment]
This is intermittent, in my experience.  They are dim because they are inactive and can’t be clicked.  Reloading fixed.


-steve

**Comment by stevenjswanson** [comment]
Also, I’ve observed it without the file browser.

**Comment by stevenjswanson** [comment]
Actually I see it consistently with the file browser changes and only very occasionally without.

**Comment by szl005** [comment]
1. Included the source code into our Moneta package so I could change the widget source directly
2. Goes from "Select" when the browser is minimized to "Load" when it's open. "Load" is no longer disabled for the same file
3. Still working on it
4. All file browser code is now in main() so everything can be run in the notebook cell itself. All Moneta code related to the file browser is wrapped up in the utils.py callback `handle_load_trace()` (basically the `file = pick_file()` and `load_file(file)` functionality combined)
5. Fixed text color opacity

**Pull request merged**
